SET search_path = risk;

INSERT INTO player VALUES (1, 'Garrett', 'red', 6, 0, 1);
INSERT INTO player VALUES (2, 'Heath', 'blue', 6, 0, 1);
INSERT INTO player VALUES (3, 'George', 'green', 6, 0, 1);

--Country Insert 
INSERT INTO country VALUES (1, 'Alaska', 'North America', NULL, NULL);
INSERT INTO country VALUES (2, 'Northwest Territory', 'North America', NULL, NULL);
INSERT INTO country VALUES (3, 'Alberta', 'North America', NULL, NULL);
INSERT INTO country VALUES (4, 'Ontario', 'North America', NULL, NULL);
INSERT INTO country VALUES (5, 'Eastern Canada', 'North America', NULL, NULL);
INSERT INTO country VALUES (6, 'Greenland', 'North America', NULL, NULL);
INSERT INTO country VALUES (7, 'Western United States', 'North America', NULL, NULL);
INSERT INTO country VALUES (8, 'Eastern United States', 'North America', NULL, NULL);
INSERT INTO country VALUES (9, 'Central America', 'North America', NULL, NULL);
INSERT INTO country VALUES (10, 'Venezuela', 'South America', NULL, NULL);
INSERT INTO country VALUES (11, 'Peru', 'South America', NULL, NULL);
INSERT INTO country VALUES (12, 'Brazil', 'South America', NULL, NULL);
INSERT INTO country VALUES (13, 'Argentina', 'South America', NULL, NULL);
INSERT INTO country VALUES (14, 'Iceland', 'Europe', NULL, NULL);
INSERT INTO country VALUES (15, 'Scandinavia', 'Europe', NULL, NULL);
INSERT INTO country VALUES (16, 'Great Britain', 'Europe', NULL, NULL);
INSERT INTO country VALUES (17, 'Northern Europe', 'Europe', NULL, NULL);
INSERT INTO country VALUES (18, 'Western Europe', 'Europe', NULL, NULL);
INSERT INTO country VALUES (19, 'Southern Europe', 'Europe', NULL, NULL);
INSERT INTO country VALUES (20, 'Russia', 'Europe', NULL, NULL);
INSERT INTO country VALUES (21, 'North Africa', 'Africa', NULL, NULL);
INSERT INTO country VALUES (22, 'Egypt', 'Africa', NULL, NULL);
INSERT INTO country VALUES (23, 'East Africa', 'Africa', NULL, NULL);
INSERT INTO country VALUES (24, 'Central Africa', 'Africa', NULL, NULL);
INSERT INTO country VALUES (25, 'South Africa', 'Africa', NULL, NULL);
INSERT INTO country VALUES (26, 'Madagascar', 'Africa', NULL, NULL);
INSERT INTO country VALUES (27, 'Ural', 'Asia', NULL, NULL);
INSERT INTO country VALUES (28, 'Siberia', 'Asia', NULL, NULL);
INSERT INTO country VALUES (29, 'Yakutsk', 'Asia', NULL, NULL);
INSERT INTO country VALUES (30, 'Kamchatka', 'Asia', NULL, NULL);
INSERT INTO country VALUES (31, 'Irkutsk', 'Asia', NULL, NULL);
INSERT INTO country VALUES (32, 'Mongolia', 'Asia', NULL, NULL);
INSERT INTO country VALUES (33, 'Japan', 'Asia', NULL, NULL);
INSERT INTO country VALUES (34, 'Afghanistan', 'Asia', NULL, NULL);
INSERT INTO country VALUES (35, 'China', 'Asia', NULL, NULL);
INSERT INTO country VALUES (36, 'Middle East', 'Asia', NULL, NULL);
INSERT INTO country VALUES (37, 'India', 'Asia', NULL, NULL);
INSERT INTO country VALUES (38, 'Southeast Asia', 'Asia', NULL, NULL);
INSERT INTO country VALUES (39, 'Indonesia', 'Australia', NULL, NULL);
INSERT INTO country VALUES (40, 'New Guinea', 'Australia', NULL, NULL);
INSERT INTO country VALUES (41, 'Western Australia', 'Australia', NULL, NULL);
INSERT INTO country VALUES (42, 'Eastern Australia', 'Australia', NULL, NULL);

--Adjacent Country Insert
INSERT INTO adjcountry VALUES (1, 2);
INSERT INTO adjcountry VALUES (1, 3);
INSERT INTO adjcountry VALUES (2, 1);
INSERT INTO adjcountry VALUES (2, 3);
INSERT INTO adjcountry VALUES (2, 4);
INSERT INTO adjcountry VALUES (2, 6);
INSERT INTO adjcountry VALUES (3, 1);
INSERT INTO adjcountry VALUES (3, 2);
INSERT INTO adjcountry VALUES (3, 4);
INSERT INTO adjcountry VALUES (3, 7);
INSERT INTO adjcountry VALUES (4, 2);
INSERT INTO adjcountry VALUES (4, 3);
INSERT INTO adjcountry VALUES (4, 5);
INSERT INTO adjcountry VALUES (4, 6);
INSERT INTO adjcountry VALUES (4, 7);
INSERT INTO adjcountry VALUES (4, 8);
INSERT INTO adjcountry VALUES (5, 4);
INSERT INTO adjcountry VALUES (5, 6);
INSERT INTO adjcountry VALUES (5, 8);
INSERT INTO adjcountry VALUES (6, 2);
INSERT INTO adjcountry VALUES (6, 4);
INSERT INTO adjcountry VALUES (6, 5);
INSERT INTO adjcountry VALUES (6, 14);
INSERT INTO adjcountry VALUES (7, 3);
INSERT INTO adjcountry VALUES (7, 4);
INSERT INTO adjcountry VALUES (7, 8);
INSERT INTO adjcountry VALUES (7, 9);
INSERT INTO adjcountry VALUES (8, 4);
INSERT INTO adjcountry VALUES (8, 5);
INSERT INTO adjcountry VALUES (8, 7);
INSERT INTO adjcountry VALUES (8, 9);
INSERT INTO adjcountry VALUES (9, 7);
INSERT INTO adjcountry VALUES (9, 8);
INSERT INTO adjcountry VALUES (9, 10);
INSERT INTO adjcountry VALUES (10, 9);
INSERT INTO adjcountry VALUES (10, 11);
INSERT INTO adjcountry VALUES (10, 12);
INSERT INTO adjcountry VALUES (11, 10);
INSERT INTO adjcountry VALUES (11, 12);
INSERT INTO adjcountry VALUES (11, 13);
INSERT INTO adjcountry VALUES (12, 10);
INSERT INTO adjcountry VALUES (12, 11);
INSERT INTO adjcountry VALUES (12, 13);
INSERT INTO adjcountry VALUES (12, 21);
INSERT INTO adjcountry VALUES (13, 11);
INSERT INTO adjcountry VALUES (13, 12);
INSERT INTO adjcountry VALUES (14, 6);
INSERT INTO adjcountry VALUES (14, 15);
INSERT INTO adjcountry VALUES (14, 16);
INSERT INTO adjcountry VALUES (15, 14);
INSERT INTO adjcountry VALUES (15, 16);
INSERT INTO adjcountry VALUES (15, 17);
INSERT INTO adjcountry VALUES (15, 20);
INSERT INTO adjcountry VALUES (16, 14);
INSERT INTO adjcountry VALUES (16, 15);
INSERT INTO adjcountry VALUES (16, 17);
INSERT INTO adjcountry VALUES (16, 18);
INSERT INTO adjcountry VALUES (17, 15);
INSERT INTO adjcountry VALUES (17, 16);
INSERT INTO adjcountry VALUES (17, 18);
INSERT INTO adjcountry VALUES (17, 19);
INSERT INTO adjcountry VALUES (17, 20);
INSERT INTO adjcountry VALUES (18, 16);
INSERT INTO adjcountry VALUES (18, 17);
INSERT INTO adjcountry VALUES (18, 19);
INSERT INTO adjcountry VALUES (18, 21);
INSERT INTO adjcountry VALUES (19, 17);
INSERT INTO adjcountry VALUES (19, 18);
INSERT INTO adjcountry VALUES (19, 20);
INSERT INTO adjcountry VALUES (19, 21);
INSERT INTO adjcountry VALUES (19, 22);
INSERT INTO adjcountry VALUES (19, 36);
INSERT INTO adjcountry VALUES (20, 15);
INSERT INTO adjcountry VALUES (20, 17);
INSERT INTO adjcountry VALUES (20, 19);
INSERT INTO adjcountry VALUES (20, 27);
INSERT INTO adjcountry VALUES (20, 34);
INSERT INTO adjcountry VALUES (20, 36);
INSERT INTO adjcountry VALUES (21, 12);
INSERT INTO adjcountry VALUES (21, 18);
INSERT INTO adjcountry VALUES (21, 19);
INSERT INTO adjcountry VALUES (21, 22);
INSERT INTO adjcountry VALUES (21, 23);
INSERT INTO adjcountry VALUES (21, 24);
INSERT INTO adjcountry VALUES (22, 19);
INSERT INTO adjcountry VALUES (22, 21);
INSERT INTO adjcountry VALUES (22, 23);
INSERT INTO adjcountry VALUES (22, 36);
INSERT INTO adjcountry VALUES (23, 21);
INSERT INTO adjcountry VALUES (23, 22);
INSERT INTO adjcountry VALUES (23, 24);
INSERT INTO adjcountry VALUES (23, 25);
INSERT INTO adjcountry VALUES (23, 26);
INSERT INTO adjcountry VALUES (23, 36);
INSERT INTO adjcountry VALUES (24, 21);
INSERT INTO adjcountry VALUES (24, 23);
INSERT INTO adjcountry VALUES (24, 25);
INSERT INTO adjcountry VALUES (25, 23);
INSERT INTO adjcountry VALUES (25, 24);
INSERT INTO adjcountry VALUES (25, 26);
INSERT INTO adjcountry VALUES (26, 23);
INSERT INTO adjcountry VALUES (26, 25);
INSERT INTO adjcountry VALUES (27, 20);
INSERT INTO adjcountry VALUES (27, 34);
INSERT INTO adjcountry VALUES (27, 35);
INSERT INTO adjcountry VALUES (27, 28);
INSERT INTO adjcountry VALUES (28, 27);
INSERT INTO adjcountry VALUES (28, 29);
INSERT INTO adjcountry VALUES (28, 31);
INSERT INTO adjcountry VALUES (28, 32);
INSERT INTO adjcountry VALUES (28, 35);
INSERT INTO adjcountry VALUES (29, 28);
INSERT INTO adjcountry VALUES (29, 30);
INSERT INTO adjcountry VALUES (29, 31);
INSERT INTO adjcountry VALUES (30, 1);
INSERT INTO adjcountry VALUES (30, 29);
INSERT INTO adjcountry VALUES (30, 31);
INSERT INTO adjcountry VALUES (30, 32);
INSERT INTO adjcountry VALUES (30, 33);
INSERT INTO adjcountry VALUES (31, 28);
INSERT INTO adjcountry VALUES (31, 29);
INSERT INTO adjcountry VALUES (31, 30);
INSERT INTO adjcountry VALUES (31, 32);
INSERT INTO adjcountry VALUES (32, 28);
INSERT INTO adjcountry VALUES (32, 30);
INSERT INTO adjcountry VALUES (32, 31);
INSERT INTO adjcountry VALUES (32, 33);
INSERT INTO adjcountry VALUES (32, 35);
INSERT INTO adjcountry VALUES (33, 30);
INSERT INTO adjcountry VALUES (33, 32);
INSERT INTO adjcountry VALUES (34, 20);
INSERT INTO adjcountry VALUES (34, 27);
INSERT INTO adjcountry VALUES (34, 35);
INSERT INTO adjcountry VALUES (34, 36);
INSERT INTO adjcountry VALUES (34, 37);
INSERT INTO adjcountry VALUES (35, 27);
INSERT INTO adjcountry VALUES (35, 28);
INSERT INTO adjcountry VALUES (35, 32);
INSERT INTO adjcountry VALUES (35, 34);
INSERT INTO adjcountry VALUES (35, 37);
INSERT INTO adjcountry VALUES (35, 38);
INSERT INTO adjcountry VALUES (36, 19);
INSERT INTO adjcountry VALUES (36, 20);
INSERT INTO adjcountry VALUES (36, 22);
INSERT INTO adjcountry VALUES (36, 23);
INSERT INTO adjcountry VALUES (36, 34);
INSERT INTO adjcountry VALUES (36, 37);
INSERT INTO adjcountry VALUES (37, 34);
INSERT INTO adjcountry VALUES (37, 35);
INSERT INTO adjcountry VALUES (37, 36);
INSERT INTO adjcountry VALUES (37, 38);
INSERT INTO adjcountry VALUES (38, 35);
INSERT INTO adjcountry VALUES (38, 37);
INSERT INTO adjcountry VALUES (38, 39);
INSERT INTO adjcountry VALUES (39, 40);
INSERT INTO adjcountry VALUES (39, 41);
INSERT INTO adjcountry VALUES (40, 39);
INSERT INTO adjcountry VALUES (40, 41);
INSERT INTO adjcountry VALUES (40, 42);
INSERT INTO adjcountry VALUES (41, 39);
INSERT INTO adjcountry VALUES (41, 40);
INSERT INTO adjcountry VALUES (41, 42);
INSERT INTO adjcountry VALUES (42, 40);
INSERT INTO adjcountry VALUES (42, 41);


--Risk Card Insert
INSERT INTO riskCards VALUES ('Wild', 1, NULL);
INSERT INTO riskCards VALUES ('Wild', 2, NULL);
INSERT INTO riskCards VALUES ('Infantry', 3, NULL);
INSERT INTO riskCards VALUES ('Infantry', 4, NULL);
INSERT INTO riskCards VALUES ('Infantry', 5, NULL);
INSERT INTO riskCards VALUES ('Infantry', 6, NULL);
INSERT INTO riskCards VALUES ('Infantry', 7, NULL);
INSERT INTO riskCards VALUES ('Infantry', 8, NULL);
INSERT INTO riskCards VALUES ('Infantry', 9, NULL);
INSERT INTO riskCards VALUES ('Infantry', 10, NULL);
INSERT INTO riskCards VALUES ('Infantry', 11, NULL);
INSERT INTO riskCards VALUES ('Infantry', 12, NULL);
INSERT INTO riskCards VALUES ('Infantry', 13, NULL);
INSERT INTO riskCards VALUES ('Infantry', 14, NULL);
INSERT INTO riskCards VALUES ('Infantry', 15, NULL);
INSERT INTO riskCards VALUES ('Infantry', 16, NULL);
INSERT INTO riskCards VALUES ('Cavalry', 17, NULL);
INSERT INTO riskCards VALUES ('Cavalry', 18, NULL);
INSERT INTO riskCards VALUES ('Cavalry', 19, NULL);
INSERT INTO riskCards VALUES ('Cavalry', 20, NULL);
INSERT INTO riskCards VALUES ('Cavalry', 21, NULL);
INSERT INTO riskCards VALUES ('Cavalry', 22, NULL);
INSERT INTO riskCards VALUES ('Cavalry', 23, NULL);
INSERT INTO riskCards VALUES ('Cavalry', 24, NULL);
INSERT INTO riskCards VALUES ('Cavalry', 25, NULL);
INSERT INTO riskCards VALUES ('Cavalry', 26, NULL);
INSERT INTO riskCards VALUES ('Cavalry', 27, NULL);
INSERT INTO riskCards VALUES ('Cavalry', 28, NULL);
INSERT INTO riskCards VALUES ('Cavalry', 29, NULL);
INSERT INTO riskCards VALUES ('Cavalry', 30, NULL);
INSERT INTO riskCards VALUES ('Artillery', 31, NULL);
INSERT INTO riskCards VALUES ('Artillery', 32, NULL);
INSERT INTO riskCards VALUES ('Artillery', 33, NULL);
INSERT INTO riskCards VALUES ('Artillery', 34, NULL);
INSERT INTO riskCards VALUES ('Artillery', 35, NULL);
INSERT INTO riskCards VALUES ('Artillery', 36, NULL);
INSERT INTO riskCards VALUES ('Artillery', 37, NULL);
INSERT INTO riskCards VALUES ('Artillery', 38, NULL);
INSERT INTO riskCards VALUES ('Artillery', 39, NULL);
INSERT INTO riskCards VALUES ('Artillery', 40, NULL);
INSERT INTO riskCards VALUES ('Artillery', 41, NULL);
INSERT INTO riskCards VALUES ('Artillery', 42, NULL);
INSERT INTO riskCards VALUES ('Artillery', 43, NULL);
INSERT INTO riskCards VALUES ('Artillery', 44, NULL);

